/* Addresses should be listed in order */
KaleidoScope_DrawAmmoCount = 0x8038EA10;
KaleidoScope_SetCursorVtx = 0x8038EF94;
KaleidoScope_QuadTextureIA8 = 0x80394200;
KaleidoScope_MoveCursorToSpecialPos = 0x80394524;
KaleidoScope_DrawQuadTextureRGBA32 = 0x80394588;
KaleidoScope_DrawCursor = 0x80394B00;
z64_AmmoItems = 0x8039EAA0;
z64_SlotAgeReqs = 0x8039F114;
z64_sEquipState = 0x8039EAB0;
z64_sEquipAnimTimer = 0x8039EAB4;
z64_sEquipMoveTimer = 0x8039EAB8;